//auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

//videos
export const LOAD_VIDEOS = 'LOAD_VIDEOS'
export const LOAD_VIDEO = 'LOAD_VIDEO'
export const LOAD_NEXT_PAGE_VIDEOS = 'LOAD_NEXT_PAGE_VIDEOS'
